pipeline {
    agent { label 'worker' }

    environment {
        DOCKER_USER = "ahmed30103"
        SONAR_HOME  = tool "sonar-scanner"
    }

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: 'latest', description: 'Frontend Docker image tag')
        string(name: 'BACKEND_DOCKER_TAG',  defaultValue: 'latest', description: 'Backend Docker image tag')
    }

    stages {
        stage("Validate Parameters") {
            steps {
                script {
                    if (params.FRONTEND_DOCKER_TAG == '' || params.BACKEND_DOCKER_TAG == '') {
                        error("FRONTEND_DOCKER_TAG and BACKEND_DOCKER_TAG must be provided.")
                    }
                }
            }
        }

        stage("Workspace cleanup") {
            steps {
                cleanWs()
            }
        }

        stage('Git: Code Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ahmed040203/MaestroOps.git'
            }
        }

        stage("Trivy: Filesystem scan") {
            steps {
                dir('Devops-Mega-Project-Jenkins-ArgoCD-EKS') {
                    sh "trivy fs --format table -o trivy-fs-report.html ."
                }
            }
        }

        stage("SonarQube: Code Analysis") {
            steps {
                withSonarQubeEnv('sonar') {
                    dir('Devops-Mega-Project-Jenkins-ArgoCD-EKS') {
                        sh """
                            ${SONAR_HOME}/bin/sonar-scanner \
                            -Dsonar.projectName=maestroops \
                            -Dsonar.projectKey=maestroops
                        """
                    }
                }
            }
        }

        stage("Docker: Build Images") {
            steps {
                script {
                    dir('Devops-Mega-Project-Jenkins-ArgoCD-EKS/backend') {
                        sh "docker build -t ${DOCKER_USER}/wanderlust-backend:${params.BACKEND_DOCKER_TAG} ."
                    }
                    dir('Devops-Mega-Project-Jenkins-ArgoCD-EKS/frontend') {
                        sh "docker build -t ${DOCKER_USER}/wanderlust-frontend:${params.FRONTEND_DOCKER_TAG} ."
                    }
                }
            }
        }

        stage("Docker: Push to DockerHub") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_U', passwordVariable: 'DOCKER_P')]) {
                        sh "echo \$DOCKER_P | docker login -u \$DOCKER_U --password-stdin"
                        sh "docker push ${DOCKER_USER}/wanderlust-backend:${params.BACKEND_DOCKER_TAG}"
                        sh "docker push ${DOCKER_USER}/wanderlust-frontend:${params.FRONTEND_DOCKER_TAG}"
                    }
                }
            }
        }
    }

    post {
        success {
            build job: "MaestroOps-CD", parameters: [
                string(name: 'FRONTEND_DOCKER_TAG', value: "${params.FRONTEND_DOCKER_TAG}"),
                string(name: 'BACKEND_DOCKER_TAG',  value: "${params.BACKEND_DOCKER_TAG}")
            ]
        }
    }
}
